//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjusteFisico
    {
        public int id { get; set; }
        public int EstadoCalaveras { get; set; }
        public int NumeroCalaveras { get; set; }
        public string ObservacionCalaveras { get; set; }
        public decimal CostoCalavera { get; set; }
        public int EstadoCristales { get; set; }
        public string ObservacionCristales { get; set; }
        public decimal CostoCristales { get; set; }
        public int EstadoDefensas { get; set; }
        public int NumeroDefensas { get; set; }
        public string ObservacionDefensas { get; set; }
        public decimal CostoDefensas { get; set; }
        public int EstadoEspejoLaterales { get; set; }
        public int NumeroEspejoLaterales { get; set; }
        public string ObservacionEspejoLaterales { get; set; }
        public decimal CostoEspejoLaterales { get; set; }
        public int EstadoRetrovisor { get; set; }
        public int NumeroRetrovisor { get; set; }
        public decimal CostoRetrovisor { get; set; }
        public int EstadoFaros { get; set; }
        public int NumeroFaros { get; set; }
        public string ObservacionFaros { get; set; }
        public decimal CostoFaros { get; set; }
        public int EstadoFacias { get; set; }
        public string ObservacionFacias { get; set; }
        public decimal CostoFacias { get; set; }
        public int EstadoHojalateria { get; set; }
        public string ObservacionHojalateria { get; set; }
        public decimal CostoHojalateria { get; set; }
        public int EstadoLlantas { get; set; }
        public int NumeroLlantas { get; set; }
        public string ObservacionLlantas { get; set; }
        public decimal CostoLlantas { get; set; }
        public int EstadoParabrisas { get; set; }
        public decimal CostoParabrisas { get; set; }
        public string ObservacionParabrisas { get; set; }
        public int EstadoPintura { get; set; }
        public string ObservacionPintura { get; set; }
        public decimal CostoPintura { get; set; }
        public bool PolizaSeguro { get; set; }
        public bool Radio { get; set; }
        public string ObservacionRadio { get; set; }
        public int EstadoRhines { get; set; }
        public int NumeroRines { get; set; }
        public string ObservacionRines { get; set; }
        public decimal CostoRines { get; set; }
        public int EstadoSalpicaderas { get; set; }
        public int NumeroSalpicaderas { get; set; }
        public string ObservacionSalpicaderas { get; set; }
        public decimal CostoSalpicaderas { get; set; }
        public int EstadoSistemaElectrico { get; set; }
        public string ObservacionSistemaElectrico { get; set; }
        public decimal CostoSistemaElectrico { get; set; }
        public int EstadoTapones { get; set; }
        public int NumeroTapones { get; set; }
        public string ObservacionTapones { get; set; }
        public decimal CostoTapones { get; set; }
        public bool TarjetaDeCirculacion { get; set; }
        public bool Verificacion { get; set; }
        public int EstadoVestiduras { get; set; }
        public string ObservacionVestiduras { get; set; }
        public decimal CostoVestiduras { get; set; }
        public decimal TotalDemerito { get; set; }
        public int IdCredito { get; set; }
        public bool Revisado { get; set; }
        public string ObservacionRetrovisor { get; set; }
        public string OtrosObservacion { get; set; }
        public decimal CostoOtros { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
