//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int Id { get; set; }
        public int IdMensualidad { get; set; }
        public int Tipo { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idAplicacionPago { get; set; }
    
        public virtual AplicacionPago AplicacionPago { get; set; }
        public virtual TipoCargo TipoCargo { get; set; }
        public virtual Mensualidad Mensualidad { get; set; }
    }
}
