//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.UsuarioRecomendados = new HashSet<UsuarioRecomendados>();
            this.ListaNegra = new HashSet<ListaNegra>();
            this.Vehiculo = new HashSet<Vehiculo>();
            this.ControlDeCambios = new HashSet<ControlDeCambios>();
        }
    
        public int Id { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public int EstadoCivil { get; set; }
        public string ActividadPreponderante { get; set; }
        public int TipoDeIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumeroCasa { get; set; }
        public string EntreCalle { get; set; }
        public string YCalle { get; set; }
        public int CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Municipio { get; set; }
        public int IdEstado { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoOficina { get; set; }
        public string Ext { get; set; }
        public string Celular { get; set; }
        public string CorreoElectronico { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoCliente { get; set; }
        public string SociedadMercantil { get; set; }
        public Nullable<int> NumeroEscrituraPublica { get; set; }
        public Nullable<System.DateTime> FechaEscritura { get; set; }
        public string NombreLicenciado { get; set; }
        public Nullable<int> NotarioPublicoNo { get; set; }
        public Nullable<int> idCiudadNotaria { get; set; }
        public Nullable<int> idEstadoNotaria { get; set; }
        public string FolioMercantilNumero { get; set; }
        public Nullable<System.DateTime> FechaFolio { get; set; }
        public Nullable<int> NoInstrumentoPublico { get; set; }
        public string NombreLicInstrumentoPublico { get; set; }
        public Nullable<int> NotarioPublicoInstrumentoPublico { get; set; }
        public Nullable<int> idCiudadInstrumentoPublico { get; set; }
        public Nullable<int> idEstadoEistrumentoPubico { get; set; }
        public string FolioMercantilIntrumentoPublico { get; set; }
        public Nullable<decimal> ControlInterno { get; set; }
        public string Conductor { get; set; }
        public Nullable<System.DateTime> FechaControlInterno { get; set; }
        public Nullable<decimal> ControlInternoInstrumento { get; set; }
        public Nullable<System.DateTime> FechaControInternoInstrumento { get; set; }
        public string OtrosDatosEscritura { get; set; }
        public string CiudadNotaria { get; set; }
        public string CiudadInstrumentoPublico { get; set; }
        public string ClaveSeguridad { get; set; }
        public bool Preferente { get; set; }
        public string NombreBeneficiario { get; set; }
        public string ApellidoPaternoBeneficiario { get; set; }
        public string ApellidoMaternoBeneficiario { get; set; }
        public string ParntescoBeneficiario { get; set; }
        public string IdentificacionBeneficiario { get; set; }
        public bool ConBeneficiario { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public string NombreR2 { get; set; }
        public string ApellidoPaternoR2 { get; set; }
        public string ApellidoMaternoR2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRecomendados> UsuarioRecomendados { get; set; }
        public virtual Estado_civil Estado_civil { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Estado Estado2 { get; set; }
        public virtual TipoDeCliente TipoDeCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegra> ListaNegra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlDeCambios> ControlDeCambios { get; set; }
        public virtual Fin_Solicitud Fin_Solicitud { get; set; }
    }
}
