//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteWeb
    {
        public int Id { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
    }
}
