//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoWeb
    {
        public int Id { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int IdAnioLA { get; set; }
        public int IdMarcaLA { get; set; }
        public int IdModeloLA { get; set; }
        public string ClaveVercion { get; set; }
        public string NombreCopleto { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string IdUsuarioSolicitud { get; set; }
        public string Comentario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual LA_Version LA_Version { get; set; }
        public virtual LA_Anios LA_Anios { get; set; }
        public virtual LA_Marcas LA_Marcas { get; set; }
        public virtual LA_Modelos LA_Modelos { get; set; }
    }
}
