//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credito()
        {
            this.AcuerdoPago = new HashSet<AcuerdoPago>();
            this.AjusteDocumental = new HashSet<AjusteDocumental>();
            this.AjusteFisico = new HashSet<AjusteFisico>();
            this.AplicacionPago = new HashSet<AplicacionPago>();
            this.Archivo = new HashSet<Archivo>();
            this.Cita = new HashSet<Cita>();
            this.ComentarioEventos = new HashSet<ComentarioEventos>();
            this.ComentariosCredito = new HashSet<ComentariosCredito>();
            this.Dispositivos = new HashSet<Dispositivos>();
            this.HistorialEstadoCobranza = new HashSet<HistorialEstadoCobranza>();
            this.HistoricoAnalisisDeCartera = new HashSet<HistoricoAnalisisDeCartera>();
            this.PromesaPago = new HashSet<PromesaPago>();
            this.ReporteEsperanzaDeCobro = new HashSet<ReporteEsperanzaDeCobro>();
            this.Credito1 = new HashSet<Credito>();
            this.DocumentacionCredito = new HashSet<DocumentacionCredito>();
            this.DispositivoDeInmovilizacion = new HashSet<DispositivoDeInmovilizacion>();
            this.HistorialDeCobro = new HashSet<HistorialDeCobro>();
            this.Mensualidad = new HashSet<Mensualidad>();
            this.Observacion = new HashSet<Observacion>();
            this.Pensionado = new HashSet<Pensionado>();
            this.ListaNegra = new HashSet<ListaNegra>();
            this.Referencia = new HashSet<Referencia>();
            this.Renovacion = new HashSet<Renovacion>();
            this.Seguro1 = new HashSet<Seguro>();
            this.PagosFactoring = new HashSet<PagosFactoring>();
            this.ControlDeCambios = new HashSet<ControlDeCambios>();
            this.PagosFactoringDescuentoCartera = new HashSet<PagosFactoringDescuentoCartera>();
            this.PagosTerceros = new HashSet<PagosTerceros>();
        }
    
        public int id { get; set; }
        public int IdVehiculo { get; set; }
        public int Plazo { get; set; }
        public decimal PrecioDeCompra { get; set; }
        public int AjustePorKilometraje { get; set; }
        public decimal AvaluoMercado { get; set; }
        public decimal AvaluoProcasa { get; set; }
        public decimal AperturaCredito { get; set; }
        public decimal GastoAdministrativo { get; set; }
        public decimal EntregaLiquida { get; set; }
        public decimal PorcentajeInteres { get; set; }
        public decimal IVA { get; set; }
        public System.DateTime FechaCredito { get; set; }
        public int Analista { get; set; }
        public int UserId { get; set; }
        public int IdTipoEstatusCredito { get; set; }
        public string CLABE { get; set; }
        public Nullable<int> TipoDePago { get; set; }
        public string Cuenta { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<System.DateTime> FechaDispersion { get; set; }
        public int idEsquema { get; set; }
        public bool Activo { get; set; }
        public int Sucursal { get; set; }
        public decimal PorcentajeAvaluo { get; set; }
        public decimal Seguro { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public decimal AdeudoTenencia { get; set; }
        public decimal AdeudoCirculacion { get; set; }
        public decimal AdeudoOtros { get; set; }
        public bool DispersionCobrada { get; set; }
        public string NombreAdeudoTenencia { get; set; }
        public Nullable<int> ReferenciaCIE { get; set; }
        public string NobreAdeudoOtros { get; set; }
        public int IdTipoDeCredito { get; set; }
        public Nullable<int> Rechazado { get; set; }
        public Nullable<int> Aviso { get; set; }
        public Nullable<int> IdPromocionSucursal { get; set; }
        public Nullable<int> IdEstatusCobranza { get; set; }
        public decimal PorcentajeCastigo { get; set; }
        public Nullable<bool> AplicarGPS { get; set; }
        public bool convenio { get; set; }
        public decimal PorcentajeCreditoLimpio { get; set; }
        public Nullable<decimal> DemeritoUnidad { get; set; }
        public Nullable<bool> ClientePreferente { get; set; }
        public Nullable<bool> PlazoForzoso { get; set; }
        public int IdEmpresaUbicacion { get; set; }
        public string DescripcionDemerito { get; set; }
        public Nullable<int> idEventocredito { get; set; }
        public Nullable<decimal> monto_reestructura { get; set; }
        public Nullable<decimal> monto_reestructura_Aprobado { get; set; }
        public Nullable<int> IdCreditoReestructurado { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public bool FacturaRequerida { get; set; }
        public bool Archivar { get; set; }
        public bool NuevoModelo { get; set; }
        public bool inprocedente { get; set; }
        public decimal CargoGPSAdelantado { get; set; }
        public Nullable<decimal> AdeudoFondeador { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<bool> EsReestructura { get; set; }
        public bool Candado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdoPago> AcuerdoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AjusteDocumental> AjusteDocumental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AjusteFisico> AjusteFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicacionPago> AplicacionPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivo { get; set; }
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioEventos> ComentarioEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosCredito> ComentariosCredito { get; set; }
        public virtual EmpresaUbicacion EmpresaUbicacion { get; set; }
        public virtual EstatusCobranza EstatusCobranza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispositivos> Dispositivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadoCobranza> HistorialEstadoCobranza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoAnalisisDeCartera> HistoricoAnalisisDeCartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromesaPago> PromesaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteEsperanzaDeCobro> ReporteEsperanzaDeCobro { get; set; }
        public virtual Esquema Esquema { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual PromocionSucursal PromocionSucursal { get; set; }
        public virtual TipoDeCredito TipoDeCredito { get; set; }
        public virtual TipoEstatusCredito TipoEstatusCredito { get; set; }
        public virtual TipoEstatusCredito TipoEstatusCredito1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito1 { get; set; }
        public virtual Credito Credito2 { get; set; }
        public virtual EventoCredito EventoCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentacionCredito> DocumentacionCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositivoDeInmovilizacion> DispositivoDeInmovilizacion { get; set; }
        public virtual Expediente Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialDeCobro> HistorialDeCobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensualidad> Mensualidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion> Observacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pensionado> Pensionado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegra> ListaNegra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencia> Referencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renovacion> Renovacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguro> Seguro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosFactoring> PagosFactoring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlDeCambios> ControlDeCambios { get; set; }
        public virtual Fin_Solicitud Fin_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosFactoringDescuentoCartera> PagosFactoringDescuentoCartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosTerceros> PagosTerceros { get; set; }
    }
}
