//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivos
    {
        public int Id { get; set; }
        public string NumeroDispositivo { get; set; }
        public Nullable<int> IdCredito { get; set; }
        public Nullable<int> IdEstatusDispositivo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEmpresaUbicacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public Nullable<System.DateTime> FechaDesinstalacion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<System.DateTime> FechaUltimaUbicacion { get; set; }
        public string IdSIS { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual EmpresaUbicacion EmpresaUbicacion { get; set; }
        public virtual EstatusDispositivo EstatusDispositivo { get; set; }
    }
}
