//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentacionCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentacionCredito()
        {
            this.AlertaDocumentoCredito = new HashSet<AlertaDocumentoCredito>();
            this.DocumentacionCreditoDetalle = new HashSet<DocumentacionCreditoDetalle>();
        }
    
        public int Id { get; set; }
        public int IdCredito { get; set; }
        public int IdDocumentacionRequerida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertaDocumentoCredito> AlertaDocumentoCredito { get; set; }
        public virtual Credito Credito { get; set; }
        public virtual DocumentacionRequerida DocumentacionRequerida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentacionCreditoDetalle> DocumentacionCreditoDetalle { get; set; }
    }
}
