//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentacionRequerida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentacionRequerida()
        {
            this.DocumentacionCredito = new HashSet<DocumentacionCredito>();
            this.Fin_DocumentacionSolicitud = new HashSet<Fin_DocumentacionSolicitud>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripción { get; set; }
        public bool activo { get; set; }
        public Nullable<int> NumeroArchivos { get; set; }
        public int Fase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentacionCredito> DocumentacionCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_DocumentacionSolicitud> Fin_DocumentacionSolicitud { get; set; }
    }
}
