//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentacionCreditoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentacionCreditoDetalle()
        {
            this.ObservacionDocumentoArchivoDetalle = new HashSet<ObservacionDocumentoArchivoDetalle>();
        }
    
        public int Id { get; set; }
        public int IdDocumentacionCredito { get; set; }
        public Nullable<int> Version { get; set; }
        public bool Activo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public Nullable<int> IdEstadoDocumentoCredito { get; set; }
    
        public virtual DocumentacionCredito DocumentacionCredito { get; set; }
        public virtual EstadoDocumentoCredito EstadoDocumentoCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionDocumentoArchivoDetalle> ObservacionDocumentoArchivoDetalle { get; set; }
    }
}
