//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiquetasPolitica
    {
        public int Id { get; set; }
        public int Politica_Id { get; set; }
        public int Etiquete_Id { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Politica Politica { get; set; }
    }
}
