//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_DocumentacionSolicitudDetalle
    {
        public int Id { get; set; }
        public int IdDocumentacionSolicitud { get; set; }
        public Nullable<int> Version { get; set; }
        public bool Activo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public Nullable<int> IdEstadoDocumentoSolicitud { get; set; }
    
        public virtual Fin_DocumentacionSolicitud Fin_DocumentacionSolicitud { get; set; }
    }
}
