//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Cita
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Comentario { get; set; }
        public string IdUserCliente { get; set; }
        public Nullable<int> IdCalendario { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<bool> Activa { get; set; }
        public Nullable<int> IdEstadoCita { get; set; }
        public Nullable<int> IdTipoCita { get; set; }
    
        public virtual Fin_Solicitud Fin_Solicitud { get; set; }
        public virtual Calendario Calendario { get; set; }
    }
}
