//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_Solicitud()
        {
            this.Fin_DocumentacionSolicitud = new HashSet<Fin_DocumentacionSolicitud>();
            this.Fin_Cita = new HashSet<Fin_Cita>();
            this.ObservacionSolicitud = new HashSet<ObservacionSolicitud>();
            this.Cliente = new HashSet<Cliente>();
            this.Credito = new HashSet<Credito>();
        }
    
        public int Id { get; set; }
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<decimal> Compra { get; set; }
        public Nullable<decimal> Venta { get; set; }
        public int IdTipoSolicitud { get; set; }
        public int IdEstadoSolicitud { get; set; }
        public int IdEsquema { get; set; }
        public Nullable<decimal> MontoSolicitado { get; set; }
        public string IdAnalista { get; set; }
        public Nullable<int> tipoDeSeguiniento { get; set; }
        public Nullable<int> IdEvento { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Esquema Esquema { get; set; }
        public virtual Fin_EstadoSolicitud Fin_EstadoSolicitud { get; set; }
        public virtual Fit_Cliente Fit_Cliente { get; set; }
        public virtual Fin_TipoSolicitud Fin_TipoSolicitud { get; set; }
        public virtual Fit_Vehiculo Fit_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_DocumentacionSolicitud> Fin_DocumentacionSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Cita> Fin_Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionSolicitud> ObservacionSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito { get; set; }
    }
}
