//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_DocumentacionSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_DocumentacionSolicitud()
        {
            this.Fin_DocumentacionSolicitudDetalle = new HashSet<Fin_DocumentacionSolicitudDetalle>();
        }
    
        public int Id { get; set; }
        public int IdSolicitud { get; set; }
        public int IdDocumentacionRequerida { get; set; }
    
        public virtual DocumentacionRequerida DocumentacionRequerida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_DocumentacionSolicitudDetalle> Fin_DocumentacionSolicitudDetalle { get; set; }
        public virtual Fin_Solicitud Fin_Solicitud { get; set; }
    }
}
