//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fit_Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fit_Vehiculo()
        {
            this.Fin_Solicitud = new HashSet<Fin_Solicitud>();
        }
    
        public int Id { get; set; }
        public int IdAnioLA { get; set; }
        public int IdMarcaLA { get; set; }
        public int IdModeloLA { get; set; }
        public string ClaveVercion { get; set; }
        public Nullable<decimal> Compra { get; set; }
        public Nullable<decimal> Venta { get; set; }
        public string NumeroDeSerie { get; set; }
        public string NumeroDeMotor { get; set; }
        public string Placas { get; set; }
        public string TarjetaDeCirculacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Color { get; set; }
        public string RFCFactura { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public string NumeroDeTarjetaDeCirculacion { get; set; }
        public Nullable<int> NumeroDePuertas { get; set; }
        public Nullable<int> NumeroDeAsientos { get; set; }
        public Nullable<int> NumeroDeCilindros { get; set; }
        public Nullable<int> IdTipoTransmision { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual LA_Anios LA_Anios { get; set; }
        public virtual LA_Version LA_Version { get; set; }
        public virtual LA_Marcas LA_Marcas { get; set; }
        public virtual LA_Modelos LA_Modelos { get; set; }
        public virtual Fit_Cliente Fit_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Solicitud> Fin_Solicitud { get; set; }
        public virtual TipoTransmision TipoTransmision { get; set; }
    }
}
