//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fit_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fit_Cliente()
        {
            this.Fit_Vehiculo = new HashSet<Fit_Vehiculo>();
            this.Fin_Solicitud = new HashSet<Fin_Solicitud>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumeroCasa { get; set; }
        public string EntreCalle { get; set; }
        public string YCalle { get; set; }
        public int CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Municipio { get; set; }
        public int IdEstado { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoOficina { get; set; }
        public string Ext { get; set; }
        public string Celular { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string IdUser { get; set; }
        public Nullable<int> IdTipoDeIdentificacion { get; set; }
        public string ActividadPreponderante { get; set; }
        public Nullable<int> IdEstadoCivil { get; set; }
        public string Nombre1 { get; set; }
        public string ApellidoPaterno1 { get; set; }
        public string ApellidoMaterno1 { get; set; }
        public string ParentescoR1 { get; set; }
        public string DireccionR1 { get; set; }
        public string TelefonoR1 { get; set; }
        public string Nombre2 { get; set; }
        public string ApellidoPaterno2 { get; set; }
        public string ApellidoMaterno2 { get; set; }
        public string TelefonoR2 { get; set; }
        public string Nombre3 { get; set; }
        public string ApellidoPaterno3 { get; set; }
        public string ApellidoMaterno3 { get; set; }
        public string TelefonoR3 { get; set; }
        public string DireccionR2 { get; set; }
        public string DireccionR3 { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fit_Vehiculo> Fit_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Solicitud> Fin_Solicitud { get; set; }
        public virtual Estado_civil Estado_civil { get; set; }
    }
}
