//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialEstadoCobranza
    {
        public int Id { get; set; }
        public int IdCredito { get; set; }
        public int IdEstatusCobranza { get; set; }
        public Nullable<int> IdMensualidad { get; set; }
        public Nullable<int> IdUsuarioEmisor { get; set; }
        public Nullable<int> IdUsuarioRevisor { get; set; }
        public string ComentarioEmisor { get; set; }
        public string ComentarioRevisor { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<bool> validado { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual EstatusCobranza EstatusCobranza { get; set; }
        public virtual Mensualidad Mensualidad { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
