//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAnalisisDeCartera
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idCredito { get; set; }
        public string cie { get; set; }
        public string cliente { get; set; }
        public Nullable<decimal> careteraAnterior { get; set; }
        public Nullable<decimal> dispercion { get; set; }
        public Nullable<decimal> pagoCapital { get; set; }
        public Nullable<decimal> capitalCondonado { get; set; }
        public Nullable<decimal> cartera { get; set; }
        public Nullable<decimal> interes { get; set; }
        public Nullable<decimal> administrativos { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> pagoMensual { get; set; }
        public Nullable<decimal> pagoMensualAFactory { get; set; }
        public Nullable<decimal> adeudoAFactory { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
