//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialDeCobro
    {
        public int IdPago { get; set; }
        public int idCredito { get; set; }
        public decimal Mensualidad { get; set; }
        public decimal Amortizacion { get; set; }
        public decimal PagoSeguro { get; set; }
        public decimal PagoGPS { get; set; }
        public decimal InteresMensual { get; set; }
        public decimal InteresMoratorio { get; set; }
        public decimal MontoPago { get; set; }
        public System.DateTime FechaDeCorte { get; set; }
        public decimal PagoACapital { get; set; }
        public int Analista { get; set; }
        public System.DateTime FechaDePago { get; set; }
        public Nullable<System.DateTime> FechaPagoCaptura { get; set; }
        public decimal pSeguro { get; set; }
        public decimal pGPS { get; set; }
        public decimal pInteresMensual { get; set; }
        public decimal pInteresMoratorio { get; set; }
        public decimal pCapital { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
