//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensualidad()
        {
            this.Cargo = new HashSet<Cargo>();
            this.Condonacion = new HashSet<Condonacion>();
            this.CrucePagoMensualidad = new HashSet<CrucePagoMensualidad>();
            this.DetalleDePago = new HashSet<DetalleDePago>();
            this.HistorialEstadoCobranza = new HashSet<HistorialEstadoCobranza>();
            this.Mora1 = new HashSet<Mora>();
        }
    
        public int Id { get; set; }
        public int IdCredito { get; set; }
        public int Mensualidad1 { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal CapitalDeudor { get; set; }
        public decimal GPS { get; set; }
        public decimal Pension { get; set; }
        public decimal Seguro { get; set; }
        public decimal Interes { get; set; }
        public decimal Amortizacion { get; set; }
        public decimal PagoAcumuladoGastoAdmon { get; set; }
        public decimal PagoAcumuladoGPS { get; set; }
        public decimal PagoAcumuladoPension { get; set; }
        public decimal PagoAcumuladoSeguro { get; set; }
        public decimal PagoAcumuladoInteres { get; set; }
        public decimal PagoAcumuladoInteresMoratorio { get; set; }
        public decimal PagoAcumuladoAmortizacion { get; set; }
        public decimal PagoCapitalDeudor { get; set; }
        public int Mora { get; set; }
        public bool Contabilizado { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> adjudicado { get; set; }
        public decimal PagoAcumuladoGastosCobrenza { get; set; }
        public bool devengable { get; set; }
        public Nullable<int> IdFacturaInteresesDebengados { get; set; }
        public Nullable<int> IdInteresAplazado { get; set; }
        public Nullable<decimal> PagoAcumuladoInteresAplazado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condonacion> Condonacion { get; set; }
        public virtual Credito Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrucePagoMensualidad> CrucePagoMensualidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDePago> DetalleDePago { get; set; }
        public virtual FacturaInteresesDebengados FacturaInteresesDebengados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadoCobranza> HistorialEstadoCobranza { get; set; }
        public virtual InteresAplazado InteresAplazado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mora> Mora1 { get; set; }
    }
}
