//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mora
    {
        public int Id { get; set; }
        public int IdMensualidad { get; set; }
        public decimal Monto { get; set; }
        public decimal MontoAplicado { get; set; }
        public bool Contabilizado { get; set; }
        public bool Activo { get; set; }
        public string Concepto { get; set; }
    
        public virtual Mensualidad Mensualidad { get; set; }
    }
}
