//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservacionCotizacion
    {
        public int Id { get; set; }
        public int IdCotizacion { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaObservacion { get; set; }
        public int IdUsuario { get; set; }
        public bool Publicar { get; set; }
    
        public virtual SolicitudCotizacion SolicitudCotizacion { get; set; }
        public virtual User User { get; set; }
    }
}
