//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoSeguro
    {
        public int id { get; set; }
        public int idSeguro { get; set; }
        public int Oficina { get; set; }
        public string Referencia { get; set; }
        public int Recibo { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal importe { get; set; }
        public int estatus { get; set; }
    
        public virtual Seguro Seguro { get; set; }
    }
}
