//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pension()
        {
            this.Pensionado = new HashSet<Pensionado>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Ciudad { get; set; }
        public decimal Mensualidad { get; set; }
        public string Telefono { get; set; }
        public string RFC { get; set; }
        public string Representante { get; set; }
        public int Banco { get; set; }
        public string ReferenciaPago { get; set; }
        public string NumeroCuenta { get; set; }
        public string CLABE { get; set; }
        public bool Activo { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pensionado> Pensionado { get; set; }
    }
}
