//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaWebItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantillaWebItem()
        {
            this.PlantillaWebItemDetalle = new HashSet<PlantillaWebItemDetalle>();
            this.PlantillaWebItemDetalle1 = new HashSet<PlantillaWebItemDetalle>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Code { get; set; }
        public string CodeLite { get; set; }
        public Nullable<int> TipoItemWebId { get; set; }
        public Nullable<int> PlantillaWebId { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> PlantillaWebUsadaId { get; set; }
    
        public virtual PlantillaWeb PlantillaWeb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillaWebItemDetalle> PlantillaWebItemDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillaWebItemDetalle> PlantillaWebItemDetalle1 { get; set; }
        public virtual TipoItemWeb TipoItemWeb { get; set; }
        public virtual PlantillaWeb PlantillaWeb1 { get; set; }
    }
}
