//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Politica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Politica()
        {
            this.EtiquetasPolitica = new HashSet<EtiquetasPolitica>();
            this.Politica1 = new HashSet<Politica>();
            this.SeguimientoPolitica = new HashSet<SeguimientoPolitica>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Ejemplo { get; set; }
        public int EstatusPolitica_Id { get; set; }
        public bool Activa { get; set; }
        public Nullable<int> Politica_Id { get; set; }
        public string url { get; set; }
    
        public virtual EstatusPolitica EstatusPolitica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtiquetasPolitica> EtiquetasPolitica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Politica> Politica1 { get; set; }
        public virtual Politica Politica2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoPolitica> SeguimientoPolitica { get; set; }
    }
}
