//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renovacion
    {
        public int id { get; set; }
        public int IdCredito { get; set; }
        public decimal PrecioDeCompra { get; set; }
        public decimal PagoACapital { get; set; }
        public System.DateTime FechaRenovacion { get; set; }
        public decimal GastosAdministrativos { get; set; }
        public decimal Intereses { get; set; }
        public decimal AvaluoProcasa { get; set; }
    
        public virtual Credito Credito { get; set; }
    }
}
