//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguro()
        {
            this.PagoSeguro = new HashSet<PagoSeguro>();
        }
    
        public int id { get; set; }
        public decimal Monto { get; set; }
        public int idCredito { get; set; }
        public int idSeguro { get; set; }
        public string Poliza { get; set; }
    
        public virtual CompaniaSeguro CompaniaSeguro { get; set; }
        public virtual Credito Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoSeguro> PagoSeguro { get; set; }
    }
}
