//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public decimal IVA { get; set; }
        public decimal GastosaAdministrativos { get; set; }
        public decimal PorcentajeAvaluoProcasa { get; set; }
        public decimal PorcentajeAperturaCredito { get; set; }
        public decimal PorcentajeIntereses { get; set; }
        public string RutaDeArchivos { get; set; }
        public decimal GPS { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string CorreoSalida { get; set; }
        public string CorreoDestino { get; set; }
        public decimal PorcentajeInteresesSinAmortizacion { get; set; }
        public decimal Pension { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public int id { get; set; }
        public decimal PorcentageAperturaSinSeguro { get; set; }
        public decimal PorcentajeAvaluoSinSeguro { get; set; }
        public decimal PorcentajeCastigo { get; set; }
        public decimal PorcentajeCreditoLimpio { get; set; }
        public Nullable<int> ModeloMinimo { get; set; }
        public int diasToleranciaMora { get; set; }
        public int diasCorteNuevaMensualidad { get; set; }
        public string RutaDeArchivosWeb { get; set; }
        public string UserFTP { get; set; }
        public string PswFTP { get; set; }
        public string HostFTP { get; set; }
        public string urlPagina { get; set; }
    }
}
