//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_perfilLaboral
    {
        public int id { get; set; }
        public int IdCategoria { get; set; }
        public string Habilidades { get; set; }
        public string Ciudad { get; set; }
        public string Email { get; set; }
        public int idUsuario { get; set; }
    }
}
