//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoyVaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AlertaDocumentoCredito = new HashSet<AlertaDocumentoCredito>();
            this.ComentarioEventos = new HashSet<ComentarioEventos>();
            this.ComentariosCredito = new HashSet<ComentariosCredito>();
            this.Credito = new HashSet<Credito>();
            this.Credito1 = new HashSet<Credito>();
            this.HistorialEstadoCobranza = new HashSet<HistorialEstadoCobranza>();
            this.HistorialEstadoCobranza1 = new HashSet<HistorialEstadoCobranza>();
            this.LA_HistotialConsulastas = new HashSet<LA_HistotialConsulastas>();
            this.ListaNegra = new HashSet<ListaNegra>();
            this.Manuales = new HashSet<Manuales>();
            this.Observacion = new HashSet<Observacion>();
            this.ObservacionDocumentoArchivoDetalle = new HashSet<ObservacionDocumentoArchivoDetalle>();
            this.Right = new HashSet<Right>();
            this.SeguimientoPolitica = new HashSet<SeguimientoPolitica>();
            this.PagosFactoring = new HashSet<PagosFactoring>();
            this.ControlDeCambios = new HashSet<ControlDeCambios>();
            this.ObservacionSolicitud = new HashSet<ObservacionSolicitud>();
            this.ObservacionCotizacion = new HashSet<ObservacionCotizacion>();
            this.PagosFactoringDescuentoCartera = new HashSet<PagosFactoringDescuentoCartera>();
            this.UserNotificacion = new HashSet<UserNotificacion>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public System.DateTime DateRegister { get; set; }
        public string CorreoElectronico { get; set; }
        public int Sucursal { get; set; }
        public string CodigoSeguridad { get; set; }
        public string RFC { get; set; }
        public bool Activo { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertaDocumentoCredito> AlertaDocumentoCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioEventos> ComentarioEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosCredito> ComentariosCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadoCobranza> HistorialEstadoCobranza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadoCobranza> HistorialEstadoCobranza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LA_HistotialConsulastas> LA_HistotialConsulastas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegra> ListaNegra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manuales> Manuales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion> Observacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionDocumentoArchivoDetalle> ObservacionDocumentoArchivoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Right> Right { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoPolitica> SeguimientoPolitica { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosFactoring> PagosFactoring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlDeCambios> ControlDeCambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionSolicitud> ObservacionSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionCotizacion> ObservacionCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosFactoringDescuentoCartera> PagosFactoringDescuentoCartera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotificacion> UserNotificacion { get; set; }
    }
}
